"""Fixed safety messages and call-to-action buttons for each triage label.

These are deliberately short, templated and reviewed — they are never
generated by the LLM. Phone numbers: 000 (Australian emergency), healthdirect
1800 022 222, Lifeline 13 11 14, Suicide Call Back Service 1300 659 467.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.rag.prompt import DISCLAIMER
from app.safety.labels import Label

CALL_000 = {"label": "Call 000", "href": "tel:000", "kind": "emergency"}
HEALTHDIRECT = {"label": "healthdirect 1800 022 222", "href": "tel:1800022222", "kind": "info"}
LIFELINE = {"label": "Lifeline 13 11 14", "href": "tel:131114", "kind": "crisis"}
LIFELINE_TEXT = {"label": "Text Lifeline 0477 13 11 14", "href": "sms:0477131114", "kind": "crisis"}
SCBS = {
    "label": "Suicide Call Back Service 1300 659 467",
    "href": "tel:1300659467",
    "kind": "crisis",
}


@dataclass(frozen=True)
class SafetyTemplate:
    """Banner title, body text and actions for a label."""

    title: str
    message: str
    actions: list[dict[str, str]] = field(default_factory=list)


TEMPLATES: dict[Label, SafetyTemplate] = {
    "crisis_self_harm": SafetyTemplate(
        title="You don't have to go through this alone",
        message=(
            "It sounds like you might be going through a really hard time. Please reach out for "
            "support now.\n\n"
            "- If you are in danger or might act on these thoughts, **call 000** now.\n"
            "- **Lifeline: 13 11 14** (24 hours, or text 0477 13 11 14).\n"
            "- **Suicide Call Back Service: 1300 659 467** (24 hours).\n\n"
            "You can come back to ask about your teeth any time."
        ),
        actions=[CALL_000, LIFELINE, LIFELINE_TEXT, SCBS],
    ),
    "emergency_airway": SafetyTemplate(
        title="This could be a medical emergency",
        message=(
            "Swelling with trouble breathing or swallowing can become life-threatening quickly.\n\n"
            "- **Call 000 now** if breathing is difficult, or go to the nearest emergency "
            "department straight away.\n"
            "- Do not wait for a dental appointment.\n"
            "- Sit upright and do not eat or drink while you wait for help."
        ),
        actions=[CALL_000],
    ),
    "medical_emergency_other": SafetyTemplate(
        title="Get emergency help now",
        message=(
            "What you describe may need emergency medical care.\n\n"
            "- **Call 000 now** (ambulance), or go to the nearest emergency department.\n"
            "- If you are not sure how urgent it is, call **healthdirect on 1800 022 222**.\n\n"
            "This assistant only gives general oral health information and cannot help with "
            "medical emergencies."
        ),
        actions=[CALL_000, HEALTHDIRECT],
    ),
    "urgent_fracture": SafetyTemplate(
        title="Get urgent care today",
        message=(
            "A possible broken or dislocated jaw needs urgent care. Go to the nearest emergency "
            "department now. Call 000 if there is heavy bleeding or trouble breathing."
        ),
        actions=[CALL_000, HEALTHDIRECT],
    ),
    "urgent_bleeding": SafetyTemplate(
        title="Bleeding that won't stop needs urgent care",
        message=(
            "Contact your dentist now. If you can't reach a dentist, go to the nearest emergency "
            "department. Call 000 if bleeding is very heavy or you feel faint."
        ),
        actions=[CALL_000, HEALTHDIRECT],
    ),
    "dental_trauma_avulsion": SafetyTemplate(
        title="Act quickly: see a dentist within 30–60 minutes",
        message=(
            "A knocked-out adult tooth has the best chance of being saved if it is put back "
            "quickly. Call a dentist or go to an emergency department now."
        ),
        actions=[HEALTHDIRECT],
    ),
    "urgent_swelling": SafetyTemplate(
        title="Facial swelling should be checked today",
        message=(
            "See a dentist or doctor today. If you can't, go to an emergency department. "
            "**Call 000** if swelling spreads to your eye or neck, or if breathing or swallowing "
            "becomes hard."
        ),
        actions=[CALL_000, HEALTHDIRECT],
    ),
    "out_of_scope": SafetyTemplate(title="", message=""),
    "none": SafetyTemplate(title="", message=""),
}

#: Used only when corpus retrieval for first aid fails. Content mirrors the ADA
#: and healthdirect knocked-out tooth guidance and must be re-checked when the
#: corpus is updated.
AVULSION_FALLBACK = (
    "**If an adult tooth is knocked out:**\n"
    "- Find the tooth and hold it by the crown (the white part), not the root.\n"
    "- If it is dirty, rinse it briefly in milk or saline. Do not scrub it.\n"
    "- If you can, gently put it back in its socket and bite on a clean cloth to hold it.\n"
    "- If you can't, keep it in milk or in the person's saliva (inside the cheek), not in water.\n"
    "- See a dentist within 30 to 60 minutes.\n"
    "- Do not put a baby tooth back in.\n\n"
    f"{DISCLAIMER}"
)

AVULSION_QUERY = "knocked out adult tooth first aid hold by crown store in milk see dentist"


def halted_message(label: Label) -> str:
    """Full reply text for labels that stop the dental flow."""
    t = TEMPLATES[label]
    return f"**{t.title}**\n\n{t.message}"
